export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDADE_SORT = "UPDADE_SORT";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const FILTER_BY_TEXT = "FILTER_BY_TEXT";
export const FILTER_BY_COLOR = "FILTER_BY_COLOR";
export const SET_ALL_COLORS = "SET_ALL_COLORS";
export const SET_ALL_MATERIALS = "SET_ALL_MATERIALS";
export const SET_MATERIAL = "SET_MATERIAL";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ALL_SIZE = "ALL_SIZE";
export const FILTER_BY_RANGE = 'FILTER_BY_RANGE'
export const FILTER_BY_CHECKBOX = 'FILTER_BY_CHECKBOX'


export const LOAD_PRODUCTS = "LOAD_PRODUCTS";